export const custom = [
	{
		name: 'Regional Indicator A',
		short_names: ['regional_indicator_a', 'a'],
		text: '',
		emoticons: [],
		keywords: ['a', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1e6.svg',
	},
    {
		name: 'Regional Indicator B',
		short_names: ['regional_indicator_b', 'b'],
		text: '',
		emoticons: [],
		keywords: ['b', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1e7.svg',
	},
    {
		name: 'Regional Indicator C',
		short_names: ['regional_indicator_c', 'c'],
		text: '',
		emoticons: [],
		keywords: ['c', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1e8.svg',
	},
    {
		name: 'Regional Indicator D',
		short_names: ['regional_indicator_d', 'd'],
		text: '',
		emoticons: [],
		keywords: ['d', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1e9.svg',
	},
    {
		name: 'Regional Indicator E',
		short_names: ['regional_indicator_e', 'e'],
		text: '',
		emoticons: [],
		keywords: ['e', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1ea.svg',
	},
    {
		name: 'Regional Indicator F',
		short_names: ['regional_indicator_f', 'f'],
		text: '',
		emoticons: [],
		keywords: ['f', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1eb.svg',
	},
    {
		name: 'Regional Indicator G',
		short_names: ['regional_indicator_g', 'g'],
		text: '',
		emoticons: [],
		keywords: ['g', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1ec.svg',
	},
    {
		name: 'Regional Indicator H',
		short_names: ['regional_indicator_h', 'h'],
		text: '',
		emoticons: [],
		keywords: ['h', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1ed.svg',
	},
    {
		name: 'Regional Indicator I',
		short_names: ['regional_indicator_i', 'i'],
		text: '',
		emoticons: [],
		keywords: ['i', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1ee.svg',
	},
    {
		name: 'Regional Indicator J',
		short_names: ['regional_indicator_j', 'j'],
		text: '',
		emoticons: [],
		keywords: ['j', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1ef.svg',
	},
    {
		name: 'Regional Indicator K',
		short_names: ['regional_indicator_k', 'k'],
		text: '',
		emoticons: [],
		keywords: ['k', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f0.svg',
	},
    {
		name: 'Regional Indicator L',
		short_names: ['regional_indicator_l', 'l'],
		text: '',
		emoticons: [],
		keywords: ['l', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f1.svg',
	},
    {
		name: 'Regional Indicator M',
		short_names: ['regional_indicator_m', 'm'],
		text: '',
		emoticons: [],
		keywords: ['m', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f2.svg',
	},
    {
		name: 'Regional Indicator N',
		short_names: ['regional_indicator_n', 'n'],
		text: '',
		emoticons: [],
		keywords: ['n', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f3.svg',
	},
    {
		name: 'Regional Indicator O',
		short_names: ['regional_indicator_o', 'o'],
		text: '',
		emoticons: [],
		keywords: ['o', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f4.svg',
	},
    {
		name: 'Regional Indicator P',
		short_names: ['regional_indicator_p', 'p'],
		text: '',
		emoticons: [],
		keywords: ['p', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f5.svg',
	},
    {
		name: 'Regional Indicator Q',
		short_names: ['regional_indicator_q', 'q'],
		text: '',
		emoticons: [],
		keywords: ['q', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f6.svg',
	},
    {
		name: 'Regional Indicator R',
		short_names: ['regional_indicator_r', 'r'],
		text: '',
		emoticons: [],
		keywords: ['r', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f7.svg',
	},
    {
		name: 'Regional Indicator S',
		short_names: ['regional_indicator_s', 's'],
		text: '',
		emoticons: [],
		keywords: ['s', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f8.svg',
	},
    {
		name: 'Regional Indicator T',
		short_names: ['regional_indicator_t', 't'],
		text: '',
		emoticons: [],
		keywords: ['t', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1f9.svg',
	},
    {
		name: 'Regional Indicator U',
		short_names: ['regional_indicator_u', 'u'],
		text: '',
		emoticons: [],
		keywords: ['u', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1fa.svg',
	},
    {
		name: 'Regional Indicator V',
		short_names: ['regional_indicator_v', 'v'],
		text: '',
		emoticons: [],
		keywords: ['v', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1fb.svg',
	},
    {
		name: 'Regional Indicator W',
		short_names: ['regional_indicator_w', 'w'],
		text: '',
		emoticons: [],
		keywords: ['w', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1fc.svg',
	},
    {
		name: 'Regional Indicator X',
		short_names: ['regional_indicator_x', 'x'],
		text: '',
		emoticons: [],
		keywords: ['x', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1fd.svg',
	},
    {
		name: 'Regional Indicator Y',
		short_names: ['regional_indicator_y', 'y'],
		text: '',
		emoticons: [],
		keywords: ['y', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1fe.svg',
	},
    {
		name: 'Regional Indicator Z',
		short_names: ['regional_indicator_z', 'z'],
		text: '',
		emoticons: [],
		keywords: ['z', 'regional', 'indicator'],
		imageUrl: 'https://twemoji.maxcdn.com/v/13.0.2/svg/1f1ff.svg',
	},
]
